[package]
name = "at2-node"
version = "0.1.0"
authors = ["Ogier Bouvier <ogier@bouvier.family>"]
edition = "2018"
license = "AGPL-3"

[dependencies]
serde = { version = "1.0.125", features = ["derive"] }
snafu = "0.6"
structopt = "0.3"
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
toml = "0.5.8"
prost = "0.7"
tonic = "0.4.2"

[dev-dependencies]
duct = "0.13.5"

[build-dependencies]
tonic-build = "0.4"
