name: deployement

on:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types: [completed]

env:
  DEPLOY_USER: at2
  DEPLOY_HOST: srv1.c4dt.org

jobs:
  deploy-ns:
    name: deploy AT2's node
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - uses: actions-rs/cargo@v1
        name: cargo build
        with:
          command: build
          args: --bin server --features server --release

      - uses: kielabokkie/ssh-key-and-known-hosts-action@v1.2.0
        with:
          ssh-host: ${{ env.DEPLOY_HOST }}
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: rsync repository
        run: >
          rsync --archive "$GITHUB_WORKSPACE/target/release/server"
          "${{ env.DEPLOY_USER }}@${{ env.DEPLOY_HOST }}:at2-node"

      - name: rebuild docker-compose
        run: >
          ssh "${{ env.DEPLOY_USER }}@${{ env.DEPLOY_HOST }}"
          docker-compose up --detach --build
